# Generated by Django 5.0.6 on 2024-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.TextField(
                blank=True,
                help_text="Загрузите видео урока",
                null=True,
                verbose_name="Видео урока",
            ),
        ),
    ]
